### PR TITLE
Fix Issue #8, Use LocalSymbolMap instead of FunctionPrototype

### LINKED ISSUE #8: Error appeared when running the examples
I generated the simple by using make, and trying to run go.py on the following decompiled code: 
```
undefined4 FUN_001011a1(undefined4 *param_1)

{
  void *pvVar1;
  
  pvVar1 = malloc(8);
  *(void **)(param_1 + 6) = pvVar1;
  FUN_0010117a(param_1 + 4);
  FUN_0010117a(*(int **)(param_1 + 6));
  *param_1 = 2;
  *(undefined *)(param_1 + 1) = 7;
  *(undefined8 *)(param_1 + 2) = 8;
  return *param_1;
}
```
And I received following errors:
```
go.py> Running...
Forwards analysis FUN_001011a1
array(ghidra.program.model.listing.Parameter, [[undefined4 * param_1@RDI:8]])
type of func_proto ghidra.program.model.pcode.FunctionPrototype@cdda9ba
type of func_proto.getParam(i) ghidra.program.model.pcode.HighSymbol@8d3ca18
Traceback (most recent call last):
  File "/home/muqi/ghidra_scripts/go.py", line 68, in <module>
    argument_varnodes = PCodeInterpreter.analyzeFunctionForward(currentFunction, pci)
  File "/home/muqi/ghidra_scripts/PCodeInterpreter.py", line 669, in analyzeFunctionForward
    argument_varnodes.append(func_proto.getParam(i).getRepresentative())
AttributeError: 'ghidra.program.model.pcode.HighSymbol' object has no attribute 'getRepresentative'
go.py> Finished!
```
My gcc version is (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
My ghidra version is: Version 9.2 , which downloaded from github on Nov-02,2020
My Java Version is: 11.0.8

Could I have some hints about how to fix this?

Thanks!

### PR DESCRIPTION
**Pull request by mark-griffin**
This fixes #8 , where switching to a LocalSymbolMap resolved the error `AttributeError: 'ghidra.program.model.pcode.HighSymbol' object has no attribute 'getRepresentative'`.

Tested on Ghidra version 9.2 (`9.2_PUBLIC_20201113`) on MacOS.

### CODE REVIEW

**Comment by mark-griffin** [comment]
Also tested that switching to `getLocalSymbolMap` still worked on version 9.1 (`ghidra_9.1_PUBLIC_20191023`) on MacOS.
